version: "3"  # optional since v1.27.0
networks:
  laravel:
services:

  database-postgres:
    container_name: booking-postgresql
    image: postgres:alpine
    restart: always
    tty: true
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5430:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - laravel

  webserver:
    image: nginx:stable
    container_name: e-mehmon-booking
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./www/e-mehmon-booking:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database-postgres
    links:
      - php
      - database-postgres
    networks:
      - laravel

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php
    restart: always
    volumes:
      - ./www/e-mehmon-booking:/var/www/html
    expose:
      - "9000"
    command: >
      bash -c "true
      && composer install
      && cp .env.example .env
      && php artisan key:generate
      && php artisan migrate
      && docker-php-entrypoint php-fpm
      "
    networks:
      - laravel

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@uzinfocom.uz
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8081:80"
    networks:
      - laravel
volumes:
  logvolume01: { }